# Generated by Django 5.1.7 on 2025-08-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memo", "0002_alter_memo_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="memo",
            options={
                "ordering": ["-pk"],
                "verbose_name": "메모",
                "verbose_name_plural": "메모 목록",
            },
        ),
    ]
