# Generated by Django 5.1.7 on 2025-08-12 13:15

import django.db.models.deletion
import league.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BundesLiga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=120, verbose_name="팀이름")),
                ("team_logo_server", models.URLField(verbose_name="서버로고주소")),
                (
                    "team_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=league.models.uuid_name_upload_to,
                    ),
                ),
                (
                    "team_id",
                    models.CharField(max_length=120, unique=True, verbose_name="팀ID"),
                ),
                ("rank", models.CharField(max_length=120, verbose_name="순위")),
                ("played", models.IntegerField(verbose_name="경기")),
                ("win", models.IntegerField(verbose_name="승")),
                ("draw", models.IntegerField(verbose_name="무")),
                ("lose", models.IntegerField(verbose_name="패")),
                ("goals_for", models.IntegerField(verbose_name="득점")),
                ("goals_against", models.IntegerField(verbose_name="실점")),
                ("goals_diff", models.IntegerField(verbose_name="득실")),
                ("form", models.CharField(max_length=120, verbose_name="최근경기")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="유럽대항전"
                    ),
                ),
                (
                    "updated_from_server",
                    models.DateTimeField(verbose_name="업데이트시간"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LaLiga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=120, verbose_name="팀이름")),
                ("team_logo_server", models.URLField(verbose_name="서버로고주소")),
                (
                    "team_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=league.models.uuid_name_upload_to,
                    ),
                ),
                (
                    "team_id",
                    models.CharField(max_length=120, unique=True, verbose_name="팀ID"),
                ),
                ("rank", models.CharField(max_length=120, verbose_name="순위")),
                ("played", models.IntegerField(verbose_name="경기")),
                ("win", models.IntegerField(verbose_name="승")),
                ("draw", models.IntegerField(verbose_name="무")),
                ("lose", models.IntegerField(verbose_name="패")),
                ("goals_for", models.IntegerField(verbose_name="득점")),
                ("goals_against", models.IntegerField(verbose_name="실점")),
                ("goals_diff", models.IntegerField(verbose_name="득실")),
                ("form", models.CharField(max_length=120, verbose_name="최근경기")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="유럽대항전"
                    ),
                ),
                (
                    "updated_from_server",
                    models.DateTimeField(verbose_name="업데이트시간"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PremierLeague",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=120, verbose_name="팀이름")),
                ("team_logo_server", models.URLField(verbose_name="서버로고주소")),
                (
                    "team_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=league.models.uuid_name_upload_to,
                    ),
                ),
                (
                    "team_id",
                    models.CharField(max_length=120, unique=True, verbose_name="팀ID"),
                ),
                ("rank", models.CharField(max_length=120, verbose_name="순위")),
                ("played", models.IntegerField(verbose_name="경기")),
                ("win", models.IntegerField(verbose_name="승")),
                ("draw", models.IntegerField(verbose_name="무")),
                ("lose", models.IntegerField(verbose_name="패")),
                ("goals_for", models.IntegerField(verbose_name="득점")),
                ("goals_against", models.IntegerField(verbose_name="실점")),
                ("goals_diff", models.IntegerField(verbose_name="득실")),
                ("form", models.CharField(max_length=120, verbose_name="최근경기")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="유럽대항전"
                    ),
                ),
                (
                    "updated_from_server",
                    models.DateTimeField(verbose_name="업데이트시간"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SerieA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=120, verbose_name="팀이름")),
                ("team_logo_server", models.URLField(verbose_name="서버로고주소")),
                (
                    "team_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=league.models.uuid_name_upload_to,
                    ),
                ),
                (
                    "team_id",
                    models.CharField(max_length=120, unique=True, verbose_name="팀ID"),
                ),
                ("rank", models.CharField(max_length=120, verbose_name="순위")),
                ("played", models.IntegerField(verbose_name="경기")),
                ("win", models.IntegerField(verbose_name="승")),
                ("draw", models.IntegerField(verbose_name="무")),
                ("lose", models.IntegerField(verbose_name="패")),
                ("goals_for", models.IntegerField(verbose_name="득점")),
                ("goals_against", models.IntegerField(verbose_name="실점")),
                ("goals_diff", models.IntegerField(verbose_name="득실")),
                ("form", models.CharField(max_length=120, verbose_name="최근경기")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="유럽대항전"
                    ),
                ),
                (
                    "updated_from_server",
                    models.DateTimeField(verbose_name="업데이트시간"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("pl_pot", models.CharField(max_length=100, verbose_name="PL포트")),
                ("ll_pot", models.CharField(max_length=100, verbose_name="LL포트")),
                ("bl_pot", models.CharField(max_length=100, verbose_name="BL포트")),
                ("sa_pot", models.CharField(max_length=100, verbose_name="SA포트")),
                ("cup_point", models.IntegerField(default=0, verbose_name="컵포인트")),
                (
                    "bl_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="league.bundesliga",
                        verbose_name="BL팀",
                    ),
                ),
                (
                    "ll_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="league.laliga",
                        verbose_name="LL팀",
                    ),
                ),
                (
                    "pl_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="league.premierleague",
                        verbose_name="PL팀",
                    ),
                ),
                (
                    "sa_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="league.seriea",
                        verbose_name="SA팀",
                    ),
                ),
            ],
        ),
    ]
