# Generated by Django 5.1.7 on 2025-08-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bundesliga",
            old_name="form",
            new_name="recent",
        ),
        migrations.RenameField(
            model_name="bundesliga",
            old_name="description",
            new_name="uefa",
        ),
        migrations.RenameField(
            model_name="laliga",
            old_name="form",
            new_name="recent",
        ),
        migrations.RenameField(
            model_name="laliga",
            old_name="description",
            new_name="uefa",
        ),
        migrations.RenameField(
            model_name="premierleague",
            old_name="form",
            new_name="recent",
        ),
        migrations.RenameField(
            model_name="premierleague",
            old_name="description",
            new_name="uefa",
        ),
        migrations.RenameField(
            model_name="seriea",
            old_name="form",
            new_name="recent",
        ),
        migrations.RenameField(
            model_name="seriea",
            old_name="description",
            new_name="uefa",
        ),
    ]
