# Generated by Django 5.1.7 on 2025-08-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0002_rename_form_bundesliga_recent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundesliga",
            name="uefa",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="유럽대항전"
            ),
        ),
        migrations.AlterField(
            model_name="laliga",
            name="uefa",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="유럽대항전"
            ),
        ),
        migrations.AlterField(
            model_name="premierleague",
            name="uefa",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="유럽대항전"
            ),
        ),
        migrations.AlterField(
            model_name="seriea",
            name="uefa",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="유럽대항전"
            ),
        ),
    ]
