# Generated by Django 5.1.7 on 2025-08-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0003_alter_bundesliga_uefa_alter_laliga_uefa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bundesliga",
            name="points",
            field=models.IntegerField(default=0, verbose_name="승점"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="laliga",
            name="points",
            field=models.IntegerField(default=0, verbose_name="승점"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="premierleague",
            name="points",
            field=models.IntegerField(default=0, verbose_name="승점"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seriea",
            name="points",
            field=models.IntegerField(default=1, verbose_name="승점"),
            preserve_default=False,
        ),
    ]
