# Generated by Django 5.1.7 on 2025-08-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "league",
            "0004_bundesliga_points_laliga_points_premierleague_points_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundesliga",
            name="recent",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="최근경기"
            ),
        ),
        migrations.AlterField(
            model_name="bundesliga",
            name="updated_from_server",
            field=models.DateTimeField(blank=True, verbose_name="업데이트시간"),
        ),
        migrations.AlterField(
            model_name="laliga",
            name="recent",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="최근경기"
            ),
        ),
        migrations.AlterField(
            model_name="laliga",
            name="updated_from_server",
            field=models.DateTimeField(blank=True, verbose_name="업데이트시간"),
        ),
        migrations.AlterField(
            model_name="premierleague",
            name="recent",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="최근경기"
            ),
        ),
        migrations.AlterField(
            model_name="premierleague",
            name="updated_from_server",
            field=models.DateTimeField(blank=True, verbose_name="업데이트시간"),
        ),
        migrations.AlterField(
            model_name="seriea",
            name="recent",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="최근경기"
            ),
        ),
        migrations.AlterField(
            model_name="seriea",
            name="updated_from_server",
            field=models.DateTimeField(blank=True, verbose_name="업데이트시간"),
        ),
    ]
