# Generated by Django 5.1.7 on 2025-08-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0005_alter_bundesliga_recent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"ordering": ["-total_point"]},
        ),
        migrations.AddField(
            model_name="player",
            name="total_draw",
            field=models.IntegerField(default=0, verbose_name="총무"),
        ),
        migrations.AddField(
            model_name="player",
            name="total_game",
            field=models.IntegerField(default=0, verbose_name="총경기"),
        ),
        migrations.AddField(
            model_name="player",
            name="total_goal_diff",
            field=models.IntegerField(default=0, verbose_name="총득실"),
        ),
        migrations.AddField(
            model_name="player",
            name="total_lose",
            field=models.IntegerField(default=0, verbose_name="총패"),
        ),
        migrations.AddField(
            model_name="player",
            name="total_point",
            field=models.IntegerField(default=0, verbose_name="총승점"),
        ),
        migrations.AddField(
            model_name="player",
            name="total_win",
            field=models.IntegerField(default=0, verbose_name="총승"),
        ),
    ]
