# Generated by Django 5.1.7 on 2025-08-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0006_alter_player_options_player_total_draw_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="premierleague",
            options={"ordering": ["rank"]},
        ),
        migrations.AlterField(
            model_name="premierleague",
            name="rank",
            field=models.IntegerField(verbose_name="순위"),
        ),
    ]
