# Generated by Django 5.1.7 on 2025-08-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0007_alter_premierleague_options_alter_premierleague_rank"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bundesliga",
            options={"ordering": ["rank"]},
        ),
        migrations.AlterModelOptions(
            name="laliga",
            options={"ordering": ["rank"]},
        ),
        migrations.AlterModelOptions(
            name="player",
            options={"ordering": ["-total_point", "-total_goal_diff"]},
        ),
        migrations.AlterModelOptions(
            name="seriea",
            options={"ordering": ["rank"]},
        ),
        migrations.AlterField(
            model_name="bundesliga",
            name="rank",
            field=models.IntegerField(verbose_name="순위"),
        ),
        migrations.AlterField(
            model_name="laliga",
            name="rank",
            field=models.IntegerField(verbose_name="순위"),
        ),
        migrations.AlterField(
            model_name="seriea",
            name="rank",
            field=models.IntegerField(verbose_name="순위"),
        ),
    ]
