# Generated by Django 5.1.7 on 2025-08-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0008_alter_bundesliga_options_alter_laliga_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bundesliga",
            options={
                "ordering": ["rank"],
                "verbose_name": "분데스리가 팀",
                "verbose_name_plural": "분데스리가 팀 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="laliga",
            options={
                "ordering": ["rank"],
                "verbose_name": "라리가 팀",
                "verbose_name_plural": "라리가 팀 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="player",
            options={
                "ordering": ["-total_point", "-total_goal_diff"],
                "verbose_name": "참가자",
                "verbose_name_plural": "참가자 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="premierleague",
            options={
                "ordering": ["rank"],
                "verbose_name": "프리미어 리그 팀",
                "verbose_name_plural": "프리미어 리그 팀 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="seriea",
            options={
                "ordering": ["rank"],
                "verbose_name": "세리에A 팀",
                "verbose_name_plural": "세리에A 팀 목록",
            },
        ),
    ]
