# Generated by Django 5.1.7 on 2025-07-30 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nick_name",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=30, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, default=django.utils.timezone.now, upload_to=""
            ),
            preserve_default=False,
        ),
    ]
