# Generated by Django 5.1.7 on 2025-08-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="", verbose_name="프로필 사진"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="이메일"),
        ),
        migrations.AlterField(
            model_name="user",
            name="nick_name",
            field=models.CharField(max_length=30, unique=True, verbose_name="닉네임"),
        ),
    ]
