# Generated by Django 5.1.7 on 2025-08-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_profile_avatar_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "프로필", "verbose_name_plural": "프로필 목록"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "사용자", "verbose_name_plural": "사용자 목록"},
        ),
    ]
