# Generated by Django 5.1.7 on 2025-08-08 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_like_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="like_users",
            field=models.ManyToManyField(
                blank=True, related_name="liked_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="reply",
            name="like_users",
            field=models.ManyToManyField(
                blank=True, related_name="liked_replies", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
