# Generated by Django 5.1.7 on 2025-08-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_comment_like_users_reply_like_users"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "카테고리",
                "verbose_name_plural": "카테고리 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "댓글", "verbose_name_plural": "댓글 목록"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-pk"],
                "verbose_name": "포스팅",
                "verbose_name_plural": "포스팅 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="reply",
            options={"verbose_name": "대댓글", "verbose_name_plural": "대댓글 목록"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "태그", "verbose_name_plural": "태그 목록"},
        ),
    ]
