# Generated by Django 5.1.7 on 2025-08-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_event_event_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_color",
            field=models.CharField(
                choices=[
                    ("text-bg-primary", "파란색"),
                    ("text-bg-secondary", "회색"),
                    ("text-bg-success", "초록색"),
                    ("text-bg-danger", "빨간색"),
                    ("text-bg-warning", "노란색"),
                    ("text-bg-info", "하늘색"),
                ],
                default="text-bg-primary",
                max_length=100,
                verbose_name="컬러",
            ),
        ),
    ]
