# Generated by Django 5.1.7 on 2025-08-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_alter_event_event_color"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-pk"],
                "verbose_name": "할일",
                "verbose_name_plural": "할일 목록",
            },
        ),
    ]
